// <auto-generated />
using System;
using BetApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BetApp.Migrations.Team
{
    [DbContext(typeof(TeamContext))]
    partial class TeamContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BetApp.Models.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Power")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a680fd7a-6b89-4352-bb45-78f53c4458e1"),
                            ImageUrl = "url_druzyny_a",
                            Name = "Drużyna A",
                            Power = 80
                        },
                        new
                        {
                            Id = new Guid("7a44900a-24d3-4100-a400-fe97f786a306"),
                            ImageUrl = "url_druzyny_b",
                            Name = "Drużyna B",
                            Power = 75
                        },
                        new
                        {
                            Id = new Guid("aba5cf22-246e-4c2b-9486-6ae92836aa5d"),
                            ImageUrl = "url_druzyny_c",
                            Name = "Drużyna C",
                            Power = 90
                        },
                        new
                        {
                            Id = new Guid("4bf6d700-2ddc-4576-aba7-fd25786511a4"),
                            ImageUrl = "url_druzyny_c",
                            Name = "Drużyna D",
                            Power = 65
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
