// <auto-generated />
using System;
using BetApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BetApp.Migrations.Bet
{
    [DbContext(typeof(BetContext))]
    [Migration("20230801191031_AddDbBetContext")]
    partial class AddDbBetContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BetApp.Models.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Course")
                        .HasColumnType("numeric");

                    b.Property<int>("WinValue")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("BetApp.Models.MatchResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Counter")
                        .HasColumnType("integer");

                    b.Property<Guid>("CouponId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("IsOver")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TeamAId")
                        .HasColumnType("uuid");

                    b.Property<int>("TeamAScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamBId")
                        .HasColumnType("uuid");

                    b.Property<int>("TeamBScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CouponId");

                    b.HasIndex("TeamAId");

                    b.HasIndex("TeamBId");

                    b.ToTable("MatchResults");
                });

            modelBuilder.Entity("BetApp.Models.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Power")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0a26bdf4-dfd1-492d-9f15-dbead21df51f"),
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/FC_Internazionale_Milano_2021.svg/2048px-FC_Internazionale_Milano_2021.svg.png",
                            Name = "Intor Mediolan",
                            Power = 90
                        },
                        new
                        {
                            Id = new Guid("95b22527-e2f7-4eb6-bbc4-d9374fd55564"),
                            ImageUrl = "https://assets.stickpng.com/images/584a9b3bb080d7616d298777.png",
                            Name = "FC.Barceluna",
                            Power = 75
                        },
                        new
                        {
                            Id = new Guid("205c1739-15bc-44a3-bfb8-6e83d8b43cee"),
                            ImageUrl = "https://logodownload.org/wp-content/uploads/2017/02/manchester-city-fc-logo-escudo-badge.png",
                            Name = "Manchester Citi",
                            Power = 90
                        },
                        new
                        {
                            Id = new Guid("868cd73f-be79-4aff-8371-d314913e1277"),
                            ImageUrl = "url_druzyny_c",
                            Name = "Lagia Warszawa",
                            Power = 100
                        },
                        new
                        {
                            Id = new Guid("43efa54c-2411-42d1-ba7e-7ee39b0107e3"),
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/hif/f/ff/Manchester_United_FC_crest.png",
                            Name = "Manchuster United",
                            Power = 65
                        },
                        new
                        {
                            Id = new Guid("5076cf58-93b0-4270-8830-b45ceb1e2f21"),
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Juventus_Logo.png/1200px-Juventus_Logo.png",
                            Name = "Juventus Turin",
                            Power = 78
                        });
                });

            modelBuilder.Entity("BetApp.Models.MatchResult", b =>
                {
                    b.HasOne("BetApp.Models.Coupon", "Coupon")
                        .WithMany("MatchResults")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BetApp.Models.Team", "TeamA")
                        .WithMany()
                        .HasForeignKey("TeamAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BetApp.Models.Team", "TeamB")
                        .WithMany()
                        .HasForeignKey("TeamBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coupon");

                    b.Navigation("TeamA");

                    b.Navigation("TeamB");
                });

            modelBuilder.Entity("BetApp.Models.Coupon", b =>
                {
                    b.Navigation("MatchResults");
                });
#pragma warning restore 612, 618
        }
    }
}
