// <auto-generated />
using System;
using BetApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BetApp.Migrations.Bet
{
    [DbContext(typeof(BetContext))]
    partial class BetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BetApp.Models.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BetValue")
                        .HasColumnType("integer");

                    b.Property<bool>("IsWin")
                        .HasColumnType("boolean");

                    b.Property<decimal>("TotalCourse")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("BetApp.Models.MatchResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BetType")
                        .HasColumnType("integer");

                    b.Property<decimal>("BetTypeCourse")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("CouponId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("IsWin")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TeamAId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TeamAScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamBId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TeamBScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CouponId");

                    b.HasIndex("TeamAId");

                    b.HasIndex("TeamBId");

                    b.ToTable("MatchResults");
                });

            modelBuilder.Entity("BetApp.Models.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Power")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d3302441-7017-459b-9e75-70d2f9ea4384"),
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/FC_Internazionale_Milano_2021.svg/2048px-FC_Internazionale_Milano_2021.svg.png",
                            Name = "Intor Mediolan",
                            Power = 90
                        },
                        new
                        {
                            Id = new Guid("e034e77c-9c0e-4c5b-adbd-16bac3d97adc"),
                            ImageUrl = "https://assets.stickpng.com/images/584a9b3bb080d7616d298777.png",
                            Name = "FC.Barceluna",
                            Power = 75
                        },
                        new
                        {
                            Id = new Guid("c7fb03ff-16ac-431d-87da-153e61669d6e"),
                            ImageUrl = "https://logodownload.org/wp-content/uploads/2017/02/manchester-city-fc-logo-escudo-badge.png",
                            Name = "Manchester Citi",
                            Power = 90
                        },
                        new
                        {
                            Id = new Guid("b66f0f60-326f-4e73-a3a0-53e91ab845bd"),
                            ImageUrl = "url_druzyny_c",
                            Name = "Lagia Warszawa",
                            Power = 100
                        },
                        new
                        {
                            Id = new Guid("89e1fcb0-7652-40c8-abcf-9d3abe3ff97b"),
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/hif/f/ff/Manchester_United_FC_crest.png",
                            Name = "Manchuster United",
                            Power = 65
                        },
                        new
                        {
                            Id = new Guid("d16ca520-7adb-427f-8da0-334447b75e55"),
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Juventus_Logo.png/1200px-Juventus_Logo.png",
                            Name = "Juventus Turin",
                            Power = 78
                        });
                });

            modelBuilder.Entity("BetApp.Models.MatchResult", b =>
                {
                    b.HasOne("BetApp.Models.Coupon", "Coupon")
                        .WithMany("MatchResults")
                        .HasForeignKey("CouponId");

                    b.HasOne("BetApp.Models.Team", "TeamA")
                        .WithMany()
                        .HasForeignKey("TeamAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BetApp.Models.Team", "TeamB")
                        .WithMany()
                        .HasForeignKey("TeamBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coupon");

                    b.Navigation("TeamA");

                    b.Navigation("TeamB");
                });

            modelBuilder.Entity("BetApp.Models.Coupon", b =>
                {
                    b.Navigation("MatchResults");
                });
#pragma warning restore 612, 618
        }
    }
}
